require("tonypires.plugins") -- This line needs to come first
require("tonypires.core.options")
require("tonypires.core.keymaps")
require("tonypires.plugins.nvim-tree")
require("tonypires.plugins.lualine")
require("tonypires.plugins.telescope")
require("tonypires.plugins.nvim-cmp")
require("tonypires.plugins.lsp.mason")
require("tonypires.plugins.lsp.lspsaga")
require("tonypires.plugins.lsp.lspconfig")
require("tonypires.plugins.lsp.null-ls")
require("tonypires.plugins.lsp.scroll")
require("tonypires.plugins.autopairs")
require("tonypires.plugins.treesitter")
require("tonypires.plugins.gitsigns")
require("tonypires.core.colorscheme")
